### PR TITLE
AWS EC2 rule - Required Tags

### PR DESCRIPTION
**Pull request by klauern**
# Description

Adds a rule and the TagSet for EC2 instances to create a user-defined rule that can require certain tags be present for compliance purposes.  Organizations often have tag conventions and standards for proper attribution to teams, and EC2 instances without these can pose a risk by being unlabeled and unknown.

## Type of change

Select the relevant option(s):

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works (optional)
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by ramimac** [comment]
Hi Nick,

This doesn't really seem to be ready for review, are you still working on this/do you expect this to work as-is/are you just looking for incremental feedback? 

Some initial observations:

1. The rule needs to be updated to the new format
2. The rule should be added to a ruleset (likely default, with enabled=false)
3. TagSets should be added to the partial
4. The rule currently only would support a single tag (so - "all our ec2 instances need to have a specific tag"). Would be nice to have it support "1 or more ARGs" - but not sure on our rule engine there, will need to dig

The idea seems solid, so I'm happy to put this on the backlog and implement myself if it's abandoned, but also don't want to step on your toes, so just let me know!

Best.

**Comment by j4v** [comment]
> This doesn't really seem to be ready for review, are you still working on this/do you expect this to work as-is/are you just looking for incremental feedback?

Let's start making use of the `Convert to draft` (https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/changing-the-stage-of-a-pull-request) functionality (as well as the`Request review` once a PR is ready). Makes it easier to track what's ready and not.

@alessandrogonzalez @JJmako @lowSoA for visibility

**Comment by klauern** [comment]
I will convert this to draft and look to remediate the missing pieces.  This was a carry-over from something our fork already had, so I wanted to get it migrated to `upstream`, but if that requires some additional work, we'll look to add it.

**Comment by j4v** [comment]
@klauern is this still relevant? If not please close the PR.

**Comment by j4v** [comment]
Closing, happy to reopen/discuss if further work is done towards this.

**Pull request closed without merging**
