### PR TITLE
import specific provider and authentication strategy only when required

### PR DESCRIPTION
**Pull request by heyweswu**

### CODE REVIEW

**Comment by thommor** [comment]
These changes look good to me, it would save needlessly loading code that isn't going to be used.

@j4v I'll let you decide whether to approve this PR.

**Comment by j4v** [comment]
@heyweswu thanks for the PR. Out of curiosity, did you notice a significant performance hit that lead you to implement this?

**Comment by heyweswu** [comment]
@j4v no not a performance hit but I'm trying to run scout on AWS lambda which has a unzipped code package limit of 250MB. I was using the branch with the new AWS api-key authentication feature when running programmatically and because that brought in the new Alibaba and Oracle providers with their dependencies it pushed the code package size over the limit.

**Comment by j4v** [comment]
@heyweswu if you're automating scout suite jobs then you might be interested in https://my.nccgroup.com/our-services/service-details/16/scout:-pscoutublic-cloud-account-monitoring.

**Comment by j4v** [comment]
Closing this PR, will merge in https://github.com/nccgroup/ScoutSuite/pull/507.

**Pull request closed without merging**
