### PR TITLE
Feature/61 ui improvements

### PR DESCRIPTION
**Pull request by Aboisier**
This PR addresses a couple of UI issues (#61). There is still quite a lot do to in my opinion, but this takes care a few irritants.

1. Navbar refactoring (you can now click outside to close the navbar
2. The last run data was moved to a modal accessible near the "about section" in the top right corner
3. Expanding a finding by clicking the `+` transforms the said `+` to a `-`, and vice versa
4. The services issues page needed a bit more guidance, I refactored it
5. Added a bit of spacing in the sidebar
6. Refactored the whole modal system. Clicking outside will now close them. They also have a fancy fade-in animation. There is no code-duplication nightmare anymore.

Sorry about all the file changes. They are mostly one-liners though. It's for a good cause.

demo-ui-improvements

### CODE REVIEW

**Comment by Remi05** [comment]
Nice work!

**Comment by j4v** [comment]
gangster

**Comment by j4v** [comment]
Couple of issues with the dark theme:

The +/- icons are also white, so they aren't very apparent:

sc_2019-01-31_09h37m38s

Under the light theme, it's clear that resources with no instances (`Groups`) are disabled:

sc_2019-01-31_09h40m36s


Under the dark theme the highlight seems reversed:

sc_2019-01-31_09h40m42s

**Comment by vifor2** [comment]
@j4v Duly noted (these changes were caused by my PR last week).

**Comment by Aboisier** [comment]
Here are two options to increase the *sense of urgency*. What do you guys think, @j4v @misg @vifor2 @zer0x64 @Remi05 ?

### Option A
image

### Option B
image

**Pull request merged**
