### PR TITLE
Feature/120 gcp sa multi project scanning

### PR DESCRIPTION
**Pull request by j4v**
This PR implements fixes for:
- https://github.com/nccgroup/ScoutSuite/issues/31
- https://github.com/nccgroup/ScoutSuite/issues/120

### CODE REVIEW

**Comment by j4v** [comment]
@rtomlinson-latacora would greatly appreciate if you can take a look.

**Comment by rtomlinson-latacora** [comment]
@j4v Looks good. I like the changes to the logic in `authenticate`. Any reason that you changed lines 93-94 in `ScoutSuite/providers/gcp/provider.py` to just `gcp` instead of keeping the service account name? I'm not sure how relevant it is but those values show up in the generated HTML report.

**Comment by j4v** [comment]
> Any reason that you changed lines

Didn't smart merge. I've added a commit so that it includes the SA email if there is one. Ideally for a user I'd put his name/email, but I think we'd have to make an extra API query for that - keeping `GCP` for that case for now.

**Comment by rtomlinson-latacora** [comment]
@j4v I just tested this code and service accounts that have an inferred project will never be able to reach the `else` clause to allow for scanning of all projects. I'm of the option that service accounts should scan all projects by default and only a specific project if defined on the CLI, regardless whether or not there is a default project in the credentials file. Let me know what you think. Thanks

**Comment by j4v** [comment]
> service accounts that have an inferred project will never be able to reach the `else`

That's correct: in order to have the SA scan all the accounts to which it has access to, you have to manually remove the default project from the credentials file.

I think that by default, Scout should only scan a user's/SA's default Project. Mainly because in an engagement, you want to make sure you have as little impact as possible. Scanning a client's whole Organization inadvertently might be bad for business!

One thing though is that currently it isn't made very clear what's being scanned, so here's what I propose:
- Adding a bit of output to tell the user what's being scanned
- Add a CLI parameter `--al` to explicitly tell Scout to scan everything the user/SA has access to.

**Comment by rtomlinson-latacora** [comment]
Adding the CLI parameter now.
If we don't want the default behavior to scan all projects, we should probably change the logic in the `ScoutSuite/providers/gcp/provider.py`'s function `authenticate` since the `else` clause essentially defaults to scanning all projects. I'll create a branch and PR again.

**Comment by j4v** [comment]
If you're going to implement this please take https://github.com/nccgroup/ScoutSuite/pull/151 into account, @zer0x64 has be refactoring the CLI.

> If we don't want the default behavior to scan all projects, we should probably change the logic in the `ScoutSuite/providers/gcp/provider.py`'s function `authenticate` since the `else` clause essentially defaults to scanning all projects.

I agree. So maybe by default if we can't determine the default project we can just exit with a message advising the user to either specify a project or run with `--all`?

**Comment by rtomlinson-latacora** [comment]
Looking at #151. Shouldn't be a problem. Are you using a logging library to print messages to stdout?

**Comment by j4v** [comment]
> Are you using a logging library to print messages to stdout?

```
from opinel.utils.console import printInfo
printInfo('string')
```

should do the job

**Comment by rtomlinson-latacora** [comment]
Unless how much information to put on the CLI. We could just show the number of projects or we can display the names of each one. I'm open to either

**Comment by j4v** [comment]
Maybe the number would be enough, otherwise it could look bad for a big org

**Comment by rtomlinson-latacora** [comment]
Just made a PR

**Pull request merged**
