### PR TITLE
Bugfix/861 Azure MonitorManagementClient Import error

### PR DESCRIPTION
**Pull request by j4v**
# Description

Fixes https://github.com/nccgroup/ScoutSuite/issues/861 by setting the exact library versions in the requirements file.

This is a short-term fix. v5.11 will address the outdated imports (see https://github.com/nccgroup/ScoutSuite/issues/862).
## Type of change

Select the relevant option(s):

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### CODE REVIEW

**Comment by murathatipoglu** [comment]
When tested with develop branch clone (version 5.10) now, I see the azure.mgmt.monitor problem is fixed now but started to get the following error:

 __main__.py L185: Authentication failure: module 'time' has no attribute 'clock'

**Comment by j4v** [comment]
@murathatipoglu thanks for raising this, it was an issue with an outdated dependency incompatible with python 3.8. Should be fixed now (in `develop`).

**Comment by i0na-k** [comment]
This occurred today when I tried to run. Has it been fixed or is there something I can do for a short term solution?

**Comment by j4v** [comment]
> Has it been fixed

This should be fixed in the `develop` branch (https://github.com/nccgroup/ScoutSuite/tree/develop).

**Pull request merged**
