### PR TITLE
Added ACM support

### PR DESCRIPTION
**Pull request by rracterr**
This is my first attempt to add to the code, please be gentle.  
Attempting to add aws ACM support, specifically to implement a rule about Transparency Logging.

### CODE REVIEW

**Comment by rracterr** [comment]
ok, so this 'appears' to work for me... but the certificates are not showing up in the UI so I must have something messed up.  It shows that there are N certificates but the actual details dont show up.

**Comment by rracterr** [comment]
Screen Shot 2019-12-27 at 11 54 24 AM

**Comment by j4v** [comment]
> ok, so this 'appears' to work for me... but the certificates are not showing up in the UI so I must have something messed up. It shows that there are N certificates but the actual details dont show up.

As mentioned in the email, looks like all that's missing is the HTML partial for certificates.

**Comment by rracterr** [comment]
Happy to fix if someone can point me to where the “html partial” is defined.

**Comment by rracterr** [comment]
Ok, I've added the partial template.

**Comment by j4v** [comment]
@rracterr we have https://github.com/nccgroup/ScoutSuite/issues/576 open for ACM. Looks like your PR already implements the first issue, would you mind implementing the second one?

**Comment by rracterr** [comment]
Screen Shot 2019-12-30 at 12 03 35 PM

**Comment by rracterr** [comment]
Screen Shot 2019-12-27 at 11 54 24 AM

**Comment by rracterr** [comment]
Calling this done... I've debugged the whole thing and it correctly flags the right certificates.

**Comment by j4v** [comment]
> Calling this done... I've debugged the whole thing and it correctly flags the right certificates.

Cheers, I'll review this week.

**Pull request merged**
