### PR TITLE
Add support for DynamoDB

### PR DESCRIPTION
**Pull request by klauern**
# Description

Adds initial support for DynamoDB to the Open Source project.

## Type of change

Select the relevant option(s):

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works (optional)
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by j4v** [comment]
Thanks @klauern will review ASAP.

Build is failing for python3.5 but looks like a minor issue.

**Comment by klauern** [comment]
No rush on this.  I marked it as a "draft" so I could continue pushing some changes.  I haven't gotten to any of the UI changes, so I have a few things that I am going to keep working on.

My list of things that I want to continue:

* smooth out the `snake_case` function
* add UI component (if missing)
* add a rule to check if a table has SSE enabled on it

**Comment by klauern** [comment]
For the Python 3.5 issue, it looks like it's related to my use of f-strings.  Is 3.5 a requirement?  Could we bump to 3.6+?

**Comment by j4v** [comment]
> No rush on this. I marked it as a "draft" so I could continue pushing some changes. 

Cool, please request the review when ready.

> For the Python 3.5 issue, it looks like it's related to my use of f-strings. Is 3.5 a requirement? Could we bump to 3.6+?

EOL for 3.5 is 2020-09-13, I guess there's no harm in deprecating support.

**Comment by klauern** [comment]
I'm not able to reproduce the error in Travis.  I did change off of f-strings, but it failed on `test-resources.py`.  I ran the same test on a 3.5 version, and it passes for me:

image

**Comment by j4v** [comment]
@klauern I've merged your PR with our proprietary implementation. All that should be missing now is the SSE check which you mentioned.

**Pull request merged**
