### PR TITLE
Bugfix/CloudFront bugs

### PR DESCRIPTION
**Pull request by x4v13r64**
Fix typo in variable name and add new protocol version.

### CODE REVIEW

**Comment by amitvocate** [comment]
i can't approve, but i definitely need this fix.
thanks, @x4v13r64

**Comment by sidyatish** [comment]
Can we merge this PR please?

**Comment by EladRovek** [comment]
Hey all,
Does anyone still have the issue or is that just me?

**Comment by PaulDMendoza** [comment]
This pull request needs to be merged in and deployed. This is killing our scans at the moment.

**Pull request merged**
