### PR TITLE
Feature/Azure CIS 1.2 Full Support

### PR DESCRIPTION
**Pull request by x4v13r64**
# Description

This PR implements all the checks from Azure CIS 1.2.

## Type of change

Select the relevant option(s):

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works (optional)
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by xnkevinnguyen** [comment]
I updated the title from CISv1.3 to CISv1.2

**Comment by j4v** [comment]
@SophieDorval & @xnkevinnguyen this is ready to merge once https://test.pypi.org/project/msgraphcore/ is on pypi.org, correct?

**Comment by xnkevinnguyen** [comment]
> @SophieDorval & @xnkevinnguyen this is ready to merge once https://test.pypi.org/project/msgraphcore/ is on pypi.org, correct?

Yes, I'm confirming it is ready once msgraphcore is officially released

**Comment by SophieDorval** [comment]
Yes, I'm also confirming that this branch is ready to be merged once msgraphcore is officially released.

**Comment by lowSoA** [comment]
Awesome work with this PR!

Although I've had a few exceptions thrown while running it (also did a `pip install -r requirements.txt --force-reinstall)`:

```
2021-04-22 15:27:24 Russ scout[24368] ERROR securitycenter.py L98: Failed to retrieve regulatory compliance standards: Operation returned an invalid status 'Bad Request'
Traceback (most recent call last):
  File "[some_dir]\ScoutSuite\ScoutSuite\providers\azure\facade\securitycenter.py", line 98, in get_regulatory_compliance_results
    compliance_standards = await run_concurrently(
  File "[some_dir]\ScoutSuite\ScoutSuite\providers\utils.py", line 26, in run_concurrently
    return await run_function_concurrently(function)
  File "[some_dir]\Python\Python38-32\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "[some_dir]\ScoutSuite\ScoutSuite\providers\azure\facade\securitycenter.py", line 99, in <lambda>
    lambda: list(client.regulatory_compliance_standards.list())
  File "[some_dir]\venv\lib\site-packages\azure\core\paging.py", line 129, in __next__
    return next(self._page_iterator)
  File "[some_dir]\venv\lib\site-packages\azure\core\paging.py", line 76, in __next__
    self._response = self._get_next(self.continuation_token)
  File "[some_dir]\venv\lib\site-packages\azure\mgmt\security\operations\_regulatory_compliance_standards_operations.py", line 111, in get_next
    raise HttpResponseError(response=response, error_format=ARMErrorFormat)
azure.core.exceptions.HttpResponseError: Operation returned an invalid status 'Bad Request'
```
The above is tracked under #884.

```
2021-04-22 15:27:32 Russ scout[24368] ERROR loggingmonitoring.py L43: Failed to retrieve resource diagnostic settings: (MissingSubscription) The request did not have a subscription or a valid tenant level resource provider.
Traceback (most recent call last):
  File "[some_dir]\ScoutSuite\ScoutSuite\providers\azure\facade\loggingmonitoring.py", line 43, in get_diagnostic_settings
    diagnostic_settings = await run_concurrently(
  File "[some_dir]\ScoutSuite\ScoutSuite\providers\utils.py", line 26, in run_concurrently
    return await run_function_concurrently(function)
  File "[some_dir]\Python\Python38-32\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "[some_dir]\ScoutSuite\ScoutSuite\providers\azure\facade\loggingmonitoring.py", line 44, in <lambda>
    lambda: client.diagnostic_settings.list(resource_id).value
  File "[some_dir]\venv\lib\site-packages\azure\mgmt\monitor\v2017_05_01_preview\operations\_diagnostic_settings_operations.py", line 272, in list
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "[some_dir]\venv\lib\site-packages\azure\core\exceptions.py", line 102, in map_error
    raise error
azure.core.exceptions.ResourceNotFoundError: (MissingSubscription) The request did not have a subscription or a valid tenant level resource provider.
```

```
2021-04-22 15:27:32 Russ scout[24368] ERROR utils.py L36: Unable to validate exception for throttling: argument of type 'RequestsTransportResponse' is not iterable
Traceback (most recent call last):
  File "[some_dir]\ScoutSuite\ScoutSuite\providers\utils.py", line 26, in run_concurrently
    return await run_function_concurrently(function)
  File "[some_dir]\Python\Python38-32\lib\concurrent\futures\thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "[some_dir]\ScoutSuite\ScoutSuite\providers\azure\facade\loggingmonitoring.py", line 44, in <lambda>
    lambda: client.diagnostic_settings.list(resource_id).value
  File "[some_dir]\venv\lib\site-packages\azure\mgmt\monitor\v2017_05_01_preview\operations\_diagnostic_settings_operations.py", line 272, in list
    map_error(status_code=response.status_code, response=response, error_map=error_map)
  File "[some_dir]\venv\lib\site-packages\azure\core\exceptions.py", line 102, in map_error
    raise error
azure.core.exceptions.ResourceNotFoundError: (MissingSubscription) The request did not have a subscription or a valid tenant level resource provider.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "[some_dir]\ScoutSuite\ScoutSuite\providers\aws\utils.py", line 36, in is_throttled
    and "Error" in e.response
TypeError: argument of type 'RequestsTransportResponse' is not iterable
```

**Comment by x4v13r64** [comment]
@SophieDorval  & @xnkevinnguyen from MS:

`We were able to reproduce the issue, and the product team is working on releasing a fix. MSRC will no longer be tracking it.`

Looks like this will be resolved _soon_!

**Comment by x64-latacora** [comment]
The library is now published under https://pypi.org/project/msgraph-core/. Removing `draft` status.

**Comment by liyun-li** [comment]
@x4v13r64 @SophieDorval @xnkevinnguyen @lowSoA 

(Trying to revive this PR:) With regards to `requirements.txt`, would it make more sense to have only `azure-cli` to maintain instead of multiple dependencies? In the wiki, should one chooses to `az login` first they'd be instructed to install `azure-cli` anyway.

**Comment by jurajsucik** [comment]
Is there anything I can help with to move this pull request ahead?

**Pull request merged**
