### PR TITLE
Fixed rules for root IAM stuff, also updated test data set

### PR DESCRIPTION
**Pull request by BastienFaure**
The JSON path used to match stuff about the IAM root account has probably changed. All my recent scout runs had greyed out items for IAM root related findings.
The rules tried to access the data at path:
```
iam.credential_reports.<root_account>
```
The key `<root_account>` does not longer exists as there is a dictionary instead, with one entry per account.

I updated all related rules and pushed a new dataset for running the tests.

### CODE REVIEW

**Comment by j4v** [comment]
Thanks @BastienFaure, will review/merge ASAP.

**Comment by BastienFaure** [comment]
@j4v I got this message when running ScoutSuite but I can't tell if this is just a warning or an error. Thanks for receiving the PR :)
details

**Comment by j4v** [comment]
> @j4v I got this message when running ScoutSuite but I can't tell if this is just a warning or an error. Thanks for receiving the PR :)
> details

That looks like the path to a few rules is broken [by the PR?]. `--debug` should provide more info.

**Comment by bishopfaure** [comment]
Found and fixed the issue, I had one of the rules not being properly written.

**Comment by j4v** [comment]
:100:

**Pull request merged**
