### PR TITLE
DELETE ME :(

### PR DESCRIPTION
**Pull request by shanedroid**
Delete Me :(

### CODE REVIEW

**Comment by j4v** [comment]
?

**Comment by ramimac** [comment]
@j4v they have a fork they meant this PR for as far as I can tell. Unfortunately there is no way to delete PRs, but I don't see anything "bad" in these artifacts, so no harm really in leaving it closed.

**Comment by shanedroid** [comment]
> @j4v they have a fork they meant this PR for as far as I can tell. Unfortunately there is no way to delete PRs, but I don't see anything "bad" in these artifacts, so no harm really in leaving it closed.

Yep. If you would be so kind as to delete this PR, it would be much appreciated. 🥺

**Comment by shanedroid** [comment]
at least I learned something 📚  

https://sethrobertson.github.io/GitFixUm/fixup.html

**Pull request closed without merging**
