### PR TITLE
Feature/120 GCP Multi-Project Scanning with single service account

### PR DESCRIPTION
**Pull request by rtomlinson-latacora**
https://github.com/nccgroup/ScoutSuite/issues/120

I made some modifications to __main__.py and __init__.py. Open to suggestions on how to abstract the nuances of the differing Providers. I saw comments about properties that were required because of AWS.

### CODE REVIEW

**Comment by j4v** [comment]
> I saw comments about properties that were required because of AWS.

The architecture was refactored from single-provider (AWS) to multi-provider, but some remnants of the original architecture have yet to be addressed.

**Comment by rtomlinson-latacora** [comment]
Silly question, but is there a command to run all the tests together?

**Comment by j4v** [comment]
> Silly question, but is there a command to run all the tests together?

The unit tests? `python nosetests tests`

**Comment by rtomlinson-latacora** [comment]
Anything we should look at in the code other than just getting the coverage back up? Or are we waiting on getting coverage up before looking at the code?

**Comment by j4v** [comment]
> Anything we should look at in the code other than just getting the coverage back up? Or are we waiting on getting coverage up before looking at the code?

Not sure what you mean @rtomlinson-latacora? Not too concerned with coverage at this point.

We'll be having a look at the changes and comment/merge shortly, thanks for the work :-).

**Comment by Aboisier** [comment]
Thanks for your contribution!
 
I noticed you added a couple of comments in your code. Some of them were mostly suggestions and did not really help understand the code. Would you mind removing those and creating issues if necessary? It will be easier to keep track of those and will help increase the readability of the code.

Other than that, I tested with two different GCP projects and it worked. Approved!

**Comment by rtomlinson-latacora** [comment]
I'll pull the comments out right now. Thanks for looking it over!

**Comment by rtomlinson-latacora** [comment]
All unnecessary comments have been removed. I ended up reverting a lot of the changes I made regarding the passing around of service_account boolean. I found that it wasn't very helpful at the moment. Please review and let me know if you have any questions. Cheers!

**Pull request merged**
