### PR TITLE
Fix role switching bug

### PR DESCRIPTION
**Pull request by j4v**
Should fix:
- https://github.com/nccgroup/ScoutSuite/issues/449
- https://github.com/nccgroup/ScoutSuite/issues/425

### CODE REVIEW

**Comment by j4v** [comment]
> Fixed the issue

Thanks @AlfredLebeau, did you test in a MFA scenario or just normal role assumption?

**Comment by AlfredLebeau** [comment]
Normal role assumption

**Comment by estemendoza** [comment]
Hi guys. Thanks for fixing this.

I just wanted to say that this broke our current scout scans for AWS and we couldn't make it work until I found this fix on the develop branch because we also tried on master and it was still failing.

Is this not happening to everybody using the latest release?

**Comment by j4v** [comment]
> Is this not happening to everybody using the latest release?

The latest release / `master` doesn't include this PR?

**Pull request merged**
