### PR TITLE
Feature/1 iam findings

### PR DESCRIPTION
**Pull request by vifor2**
PR for https://github.com/nccgroup/ScoutSuite-Proprietary/issues/1
- Lack of Access Key Rotation : was already done.
- Lack of AWS CMK Key Rotation : now fetching the data of an additional service (KMS) : to see the variation of the finding's output you can toggle the rotation of one or multiple keys here :
[removed as included AWS account number]

The finding can be seen here :
image
- Managed Policy Allows NotActions : was already done.
- User With Password and Key Enabled : was already done.

### CODE REVIEW

**Comment by vifor2** [comment]
Proprietary part : https://github.com/nccgroup/ScoutSuite-Proprietary/pull/65

**Comment by j4v** [comment]
> * User With Password and Key Enabled : was already done.

Ah I see why I missed this, it's disabled in the default ruleset:
```
        "iam-user-with-password-and-key.json": [
            {
                "enabled": false,
                "level": "warning"
            }
```

**Comment by vifor2** [comment]
> A view should also be implemented for KMS key resources.

Alright, will do

**Comment by vifor2** [comment]
Sorry for the delay, been pretty busy this week 😐 
Added the view for KMS keys, attributes visible are alias name, descrition, id and arn. The page being accessible under Security-->KMS-->Keys
kms

**Pull request merged**
