### PR TITLE
Release/5.0.0-beta

### PR DESCRIPTION
**Pull request by Aboisier**
PR for the 5.0.0-beta release.

What changed:
* Python 2.7 and 3.4 have been **deprecated**
* The whole resources fetching architecture was refactored ([see the documentation](https://github.com/nccgroup/ScoutSuite/wiki/(Draft)-Resources-fetching-system-architecture) for more details) and AWS and Azure were migrated to that new architecture
* A new flag was added (`--max-workers`) which allows specifying the exact number of workers (threads) Scout will use. This will replace `--thread-config`, which is less verbose. The new flag can be used with Azure and AWS only as GCP has not yet been refactored.
* Performance was improved
* The logging system was refactored
* A _Resources summary_ page was added (available through the top-right menu)
* UI improvements were made
* Bugs were fixed
* Some (AWS) resources that were not used for findings or surface attack analysis have been removed
  * EC2: `customer_gateways`, `vpn_gateways`, `vpn_connections`, `route_tables`, `peering_connections`
  * Route53: `hosted_zones`
  * SNS: `subscriptions` (already included in topics)
  * ELBv2: `ssl_policies`
  * ELB: `elb_policies`

### CODE REVIEW

**Comment by j4v** [comment]
Two things:
- Can we number this one something like 5.0.0-beta? As GCP isn't refactored I'd wait until we release a new major number.
- Can we review/approve/merge https://github.com/nccgroup/ScoutSuite/pull/294 before merging this one to `master`, as it fixes a number of bugs.

**Comment by Aboisier** [comment]
> * Can we number this one something like 5.0.0-beta? As GCP isn't refactored I'd wait until we release a new major number.
Good point, forgot to add the -beta.

> * Can we review/approve/merge #294 before merging this one to `master`, as it fixes a number of bugs.

I suggest we wait since your PR isn't exactly a quick fix (it changes like >60 files) and this is only a beta. We can do another release next week. We could also make this one an alpha, and promote it to beta next week when we release GCP. It's your call though, we can also delay this one a few days and merge your stuff in.

**Comment by j4v** [comment]
> We could also make this one an alpha, and promote it to beta next week when we release GCP.

I like this approach.

What do you think of releasing alpha & beta only in GH but not in pypi? Are we confident enough in the refactoring that it won't block anyone doing a pip upgrade (mentioned a few issues with AWS in slack)?

**Comment by misg** [comment]
Some (AWS) resources that were not used for findings or surface attack analysis have been removed, I would mentioned them in the release notes (since some of them were actually displayed in Scout Suite reports, some users could be surprized):

- **EC2**: `customer_gateways`, `vpn_gateways`, `vpn_connections`, `route_tables`, `peering_connections`
- **Route53**: `hosted_zones`
-  **SNS**: `subscriptions` (already included in `topics`)
- **ELBv2**: `ssl_policies`
- **ELB**: `elb_policies`

**Comment by j4v** [comment]
> since some of them were actually displayed in Scout Suite reports

If they were displayed in the report couldn't they be useful? I thought they were in the code but not referenced anywhere.
I'd open an issue to track this, for example ELB/ELBv2 policies are por

**Comment by Aboisier** [comment]
> What do you think of releasing alpha & beta only in GH but not in pypi?

The GH only release sounds good to me! 👌

**Comment by misg** [comment]
> > since some of them were actually displayed in Scout Suite reports
> 
> If they were displayed in the report couldn't they be useful? I thought they were in the code but not referenced anywhere.
> I'd open an issue to track this, for example ELB/ELBv2 policies are quite useful to review even if we don't have all the findings we should at this point.

My bad.
So I double-checked and there was no reference at all of `customer_gateways` (ec2), `vpn_gateways` (ec2), `vpn_connections` (ec2), `route_tables` (ec2), `subscriptions` (sns, already included in the `topics` resources) and `ssl_policies` (ELBv2).

But `peering_connections` and `elb_policies` were indeed included in Scout Suite reports, I'll open an issue about that.

**Comment by Aboisier** [comment]
@j4v @misg @vifor2 are you guys ok with shipping this? I'd like to have at least another person sign off before I merge.

**Comment by j4v** [comment]
> @j4v @misg @vifor2 are you guys ok with shipping this?

Yes go for it (GH-only release). We can release `5.0.0-beta2` (?) new w/e.

**Pull request merged**
