### PR TITLE
Improve implementation of Azure NSG port ranges

### LINKED ISSUE #793: Bug: Poor implementation of Azure NSG ports
See https://github.com/nccgroup/ScoutSuite/issues/698#issuecomment-645229279.

Need to improve this implementation.

### PR DESCRIPTION
**Pull request by lowSoA**
# Description

- Addressed the issue where port ranges were parsed into a long list of ports, specially the default inbound/outbound rules
- As a result, the final JS file is much smaller which could affect host performance if many default rules are in place

Fixes #793

## Type of change

Select the relevant option(s):

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works (optional)
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by j4v** [comment]
Great! Does https://github.com/nccgroup/ScoutSuite/blob/3fde85ee3c36067ec8f35e84eecc83d2cb8df19e/ScoutSuite/providers/azure/rules/findings/network-security-groups-rule-inbound-internet-all.json also require an update?

**Comment by j4v** [comment]
If you have the time, it would be good to check if we can add any rules as described in https://github.com/nccgroup/ScoutSuite/issues/570, since it relates to the same functionality.

**Comment by lowSoA** [comment]
> Great! Does https://github.com/nccgroup/ScoutSuite/blob/3fde85ee3c36067ec8f35e84eecc83d2cb8df19e/ScoutSuite/providers/azure/rules/findings/network-security-groups-rule-inbound-internet-all.json also require an update?

It does not need an update since looks for `*` or `0-65535` in `destination_port_ranges` parameter and the new update was primarily around the `destination_ports` parameter, which affects the `network-security-groups-rule-inbound-service.json` rule directly.

I've had `destination_port_ranges` parameter with the rule you mentioned in mind but it doesn't seem to need an update (IMO).

> If you have the time, it would be good to check if we can add any rules as described in #570, since it relates to the same functionality.

I'll look into this.

**Comment by j4v** [comment]
Brilliant! It makes a huge difference, even for a small subscription:

```sh
(venv) ~/Git/ScoutSuite (develop ✘)✭ ᐅ l [report]

-rw-rw-r-- 1 user user 5.9M Sep 19 10:29 [report]

(venv) ~/Git/ScoutSuite (bug/793-azure-nsg-reports ✘)✭ ᐅ l [report]

-rw-rw-r-- 1 user user 20K Sep 19 10:29 [report]
```

**Pull request merged**
